apiVersion: v1
kind: Pod
metadata:
  name: php-mysql
  # Dùng để liên kết với selector của service: danh sách selector là con của danh sách labels.
  labels:
    app.kubernetes.io/name: php-mysql  
spec:
  containers:
  - name: php
    image: php
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: app_data
      mountPath: "/var/www/html/"
  - name: db
    image: mysql:8.0.27
    ports:
    - containerPort: 3306
      # name: 
    - containerPort: 33060
      # name:
    volumeMounts:
    - name: db_data
      mountPath: "/var/lib/mysql"
  volumes:
  - name: app_data
    emptyDir: {}
  - name: db_data
    emptyDir: {}    
---
apiVersion: v1
kind: Service
metadata:
  name: php-mysql
spec:
  selector:
    app.kubernetes.io/name: php-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # http 
    - protocol: TCP
      port: 3306
      targetPort: 3306 # http 
    - protocol: TCP
      port: 33060
      targetPort: 33060 # http             